import { MinWage } from "@/app/data/types";
import { filterMinWage } from "./utils";

const users = [
  {
    id: "587e7dcb2999b746c7e5cf03",
    creationDate: "2017-01-17 20:25:47+00:00",
    age: 31,
    hourlyRate: 12,
    sits: 0,
    latestReviewDate: "",
    reviewerCount: 0,
    dBSChecked: true,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: false,
    hasProfileVideo: false,
    oFSTEDRegistered: false,
    newBornExperience: true,
    hasUKDrivingLicense: null,
    firstAidTrained: true,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "",
  },
  {
    id: "587f682d2999b746c7e5cfaf",
    creationDate: "2017-01-18 13:05:49+00:00",
    age: 47,
    hourlyRate: 9,
    sits: 0,
    latestReviewDate: "",
    reviewerCount: 0,
    dBSChecked: true,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: false,
    hasProfileVideo: false,
    oFSTEDRegistered: null,
    newBornExperience: false,
    hasUKDrivingLicense: null,
    firstAidTrained: false,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "",
  },
  {
    id: "587f9dca2999b746c7e5cfdc",
    creationDate: "2017-01-18 16:54:34+00:00",
    age: 30,
    hourlyRate: 10,
    sits: 0,
    latestReviewDate: "",
    reviewerCount: 0,
    dBSChecked: true,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: false,
    hasProfileVideo: false,
    oFSTEDRegistered: true,
    newBornExperience: false,
    hasUKDrivingLicense: null,
    firstAidTrained: true,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "{'value': {}}",
  },
  {
    id: "587fbb512999b746c7e5d006",
    creationDate: "2017-01-18 19:00:33+00:00",
    age: 30,
    hourlyRate: 10,
    sits: 0,
    latestReviewDate: "",
    reviewerCount: 0,
    dBSChecked: true,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: true,
    hasProfileVideo: false,
    oFSTEDRegistered: false,
    newBornExperience: true,
    hasUKDrivingLicense: null,
    firstAidTrained: false,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "",
  },
  {
    id: "5a2f97e492647b2acd685f6b",
    creationDate: "2017-12-12 08:48:36+00:00",
    age: 20,
    hourlyRate: 12.5,
    sits: 0,
    latestReviewDate: "",
    reviewerCount: 0,
    dBSChecked: false,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: true,
    hasProfileVideo: false,
    oFSTEDRegistered: false,
    newBornExperience: true,
    hasUKDrivingLicense: null,
    firstAidTrained: false,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "",
  },
  {
    id: "5a971099ea23487db195348a",
    creationDate: "2018-02-28 20:27:05+00:00",
    age: 20,
    hourlyRate: 9.5,
    sits: 2,
    latestReviewDate: "2021-04-09T15:37:51.715Z",
    reviewerCount: 1,
    dBSChecked: null,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: true,
    hasProfileVideo: false,
    oFSTEDRegistered: null,
    newBornExperience: false,
    hasUKDrivingLicense: null,
    firstAidTrained: false,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "",
  },
  {
    id: "592956fd113b7952074d3be7",
    creationDate: "2017-05-27 10:37:49+00:00",
    age: 21,
    hourlyRate: 7,
    sits: 15,
    latestReviewDate: "2019-04-13T22:44:39.718Z",
    reviewerCount: 1,
    dBSChecked: false,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: false,
    hasProfileVideo: false,
    oFSTEDRegistered: false,
    newBornExperience: false,
    hasUKDrivingLicense: null,
    firstAidTrained: false,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "{'value': {'french': True}}",
  },
  {
    id: "5a22632c9345a834496e24a6",
    creationDate: "2017-12-02 08:24:12+00:00",
    age: 21,
    hourlyRate: 8,
    sits: 0,
    latestReviewDate: "",
    reviewerCount: 0,
    dBSChecked: false,
    verifiedDBS: false,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: false,
    hasProfileVideo: false,
    oFSTEDRegistered: null,
    newBornExperience: false,
    hasUKDrivingLicense: null,
    firstAidTrained: false,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "",
  },
  {
    id: "5a4791e8f86d55034fc1903e",
    creationDate: "2017-12-30 13:17:28+00:00",
    age: 21,
    hourlyRate: 12,
    sits: 0,
    latestReviewDate: "",
    reviewerCount: 0,
    dBSChecked: true,
    verifiedDBS: true,
    bubbleVerified: false,
    idVerified: true,
    referenceChecked: false,
    hasProfileVideo: false,
    oFSTEDRegistered: null,
    newBornExperience: false,
    hasUKDrivingLicense: null,
    firstAidTrained: true,
    specialNeedsExperience: false,
    otherLanguagesSpoken: "",
  },
];

describe("filterMinWage", () => {
  it("sorts group correctly", () => {
    const minWageUsers: MinWage[] = filterMinWage(users);
    expect(minWageUsers).toStrictEqual([
      {
        ageGroup: "<18",
        below: 0,
        above: 0,
      },
      {
        ageGroup: "18-20",
        below: 0,
        above: 2,
      },
      { ageGroup: "21-22", below: 2, above: 1 },
      { ageGroup: "23+", below: 3, above: 1 },
    ]);
  });
});
